import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run build:runtime` (terser output, gitignored). Linting
    // minified bundles reports hundreds of findings about code nobody wrote,
    // which is enough noise to make `npm run lint` useless as a gate. Only
    // shows up on a machine that has actually run the runtime build, which is
    // why it went unnoticed.
    "runtime/dist/**",
  ]),
  {
    // Hand-written ES5 creative units, not app code. Two default rules model
    // them wrongly, and leaving them on kept `npm run lint` permanently red —
    // which is what made it useless as a CI gate.
    //
    // - `no-this-alias`: `var self = this` is the ES5 closure idiom these units
    //   are written in on purpose. They run inside third-party players with no
    //   transpile step, so arrow functions are not an option.
    // - `no-unused-vars`: each template declares `var TEMPLATE`, which is read
    //   by `runtime/lib/vpaid-base.js` only after `runtime/build.mjs`
    //   concatenates the two files. ESLint lints them separately and cannot see
    //   the reference; the same goes for `getVPAIDAd`, which the player looks up
    //   on the global object rather than importing.
    files: ["runtime/**/*.js"],
    rules: {
      "@typescript-eslint/no-this-alias": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
]);

export default eslintConfig;
