import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run build:runtime` (terser output, gitignored). Linting
    // minified bundles reports hundreds of findings about code nobody wrote,
    // which is enough noise to make `npm run lint` useless as a gate. Only
    // shows up on a machine that has actually run the runtime build, which is
    // why it went unnoticed.
    "runtime/dist/**",
  ]),
]);

export default eslintConfig;
