/**
 * creosmith-web — the Next.js app on Cloudflare Workers, through OpenNext
 * (ADR-0029 §2).
 *
 * `opennextjs-cloudflare build` writes the app's Worker to `.open-next/`; this
 * entry wraps it for the three things the app needs that OpenNext does not do:
 *
 *   - **The snapshot store's KV binding.** Bindings arrive with each request,
 *     not at module load, and the Next server code reads the store through a
 *     registry it cannot see `env` from (lib/serving/registry.ts).
 *   - **The canonical origin.** OpenNext sets `__NEXT_PRIVATE_ORIGIN` — what a
 *     server action's redirect is rendered from — once, from the first request
 *     the isolate ever sees. This Worker answers two hosts: the app's, and the
 *     ad domain's pages forwarded by creosmith-ads. Whichever came first would
 *     win, so it is pinned to the app's origin.
 *   - **The daily audit.** Vercel's cron called `/api/cron/health`; here the
 *     scheduled handler does, in-process, and fails the run when the route
 *     reports drift, so the failure shows in the Worker's cron history.
 */
// Generated by `opennextjs-cloudflare build`: absent before a build, untyped
// JavaScript after one — so neither `@ts-expect-error` (unused once it exists)
// nor a typed import fits. Its shape is asserted below.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { default as handler } from "../../.open-next/worker.js";
import { bindingNamespace, type KvBinding } from "../../lib/serving/kv";
import { registerSnapshotNamespace } from "../../lib/serving/registry";
import { SNAPSHOT_CACHE_SECONDS } from "../../lib/serving/store";

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

interface Env {
  SNAPSHOTS: KvBinding;
  NEXT_PUBLIC_SITE_URL: string;
  CRON_SECRET?: string;
  [binding: string]: unknown;
}

interface OpenNextHandler {
  fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response>;
}

const app = handler as OpenNextHandler;

/** The daily schedule in wrangler.jsonc; any other is the reconciler's. */
const DAILY = "0 3 * * *";

function prepare(env: Env): void {
  registerSnapshotNamespace(bindingNamespace(env.SNAPSHOTS, SNAPSHOT_CACHE_SECONDS));
}

function pinOrigin(env: Env): void {
  const origin = (env.NEXT_PUBLIC_SITE_URL ?? "").replace(/\/+$/, "");
  if (origin) process.env.__NEXT_PRIVATE_ORIGIN = origin;
}

const worker = {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    prepare(env);
    // Before the app runs, for every request after the first; and after it,
    // because the first request's own initialisation overwrites it.
    pinOrigin(env);
    try {
      return await app.fetch(request, env, ctx);
    } finally {
      pinOrigin(env);
    }
  },

  async scheduled(controller: { cron: string }, env: Env, ctx: ExecutionContext): Promise<void> {
    prepare(env);
    pinOrigin(env);
    // Two schedules (wrangler.jsonc): the daily audit, and the reconciler every
    // ten minutes. At 03:00 both fire, which is harmless.
    const route = controller.cron === DAILY ? "/api/cron/health" : "/api/cron/reconcile";
    if (!env.CRON_SECRET) throw new Error(`[cron] CRON_SECRET is not set; ${route} not run`);
    const site = (env.NEXT_PUBLIC_SITE_URL ?? "https://creosmith.com").replace(/\/+$/, "");
    const response = await app.fetch(
      new Request(`${site}${route}`, {
        headers: { authorization: `Bearer ${env.CRON_SECRET}` },
      }),
      env,
      ctx,
    );
    // Thrown, so the run shows as failed in the Worker's cron history: a 503
    // from either route is drift that is still there.
    if (!response.ok) {
      throw new Error(`[cron] ${route} ${response.status} ${(await response.text()).slice(0, 500)}`);
    }
  },
};

export default worker;
