// GENERATED by `npm run runtime:push` — do not edit by hand.
//
// Maps the logical runtime keys stored in `templates.runtime_keys` to the
// content-addressed objects that actually hold the bytes (ADR-0017): R2, served
// from the media host (ADR-0029). Committed on purpose: the app and the ad Worker
// read it at build time, so resolving a unit URL costs no network call on the ad
// path.
//
// TypeScript rather than JSON so it loads identically under the Next bundler and
// under plain `node` (which demands an import attribute for JSON), and so the
// shape is type-checked.

export interface RuntimeManifest {
  generatedAt: string | null;
  assets: Record<string, { url: string; sha256: string }>;
}

export const RUNTIME_MANIFEST: RuntimeManifest = {
  "generatedAt": "2026-10-03T10:01:55.663Z",
  "assets": {
    "age-gate/vpaid.js": {
      "url": "https://media.smithcdn.net/runtime/age-gate/vpaid.29339a78.js",
      "sha256": "29339a780b9da4b35773fadd79a78ee4429d92ef060f979c14f84b7550c7fe5f"
    },
    "pick-message/vpaid.js": {
      "url": "https://media.smithcdn.net/runtime/pick-message/vpaid.573fbd2b.js",
      "sha256": "573fbd2b047420bf8a067ff1fbd46ba245436839ae6ce5f364832ab56dde469b"
    },
    "quiz/vpaid.js": {
      "url": "https://media.smithcdn.net/runtime/quiz/vpaid.8eeec37b.js",
      "sha256": "8eeec37b4944c14ad272522f5f32c06f5d281137e0de62e5b6ddf41b15e279da"
    },
    "scratch-reveal/vpaid.js": {
      "url": "https://media.smithcdn.net/runtime/scratch-reveal/vpaid.25bb8dc2.js",
      "sha256": "25bb8dc2a4aad0c98ba301c66bb039a4177c1f70feb193c2f43f58694d2117e8"
    },
    "shoppable/simid/index.html": {
      "url": "https://media.smithcdn.net/runtime/shoppable/simid/index.ede9a3a6.html",
      "sha256": "ede9a3a68d0cde4ce17cca4c227d069d8ac56907149048f8eff79c2b7818f77c"
    },
    "shoppable/vpaid/unit.js": {
      "url": "https://media.smithcdn.net/runtime/shoppable/vpaid/unit.a77fdfff.js",
      "sha256": "a77fdffff6ef75abfbfc91b9bb2e3fa763f7b6f24abb74031cbbd90a19b35bea"
    },
    "slider/vpaid.js": {
      "url": "https://media.smithcdn.net/runtime/slider/vpaid.2433b694.js",
      "sha256": "2433b694630b6d72ebcbd97e53f128c85888b0d19ab81cad53b293d95824df6f"
    }
  }
};
