// GENERATED by `npm run runtime:push` — do not edit by hand.
//
// Maps the logical runtime keys stored in `templates.runtime_keys` to the
// content-addressed CDN objects that actually hold the bytes (ADR-0017).
// Committed on purpose: the app reads it at build time, so resolving a unit URL
// costs no network call on the ad path.
//
// TypeScript rather than JSON so it loads identically under the Next bundler and
// under plain `node` (which demands an import attribute for JSON), and so the
// shape is type-checked.

export interface RuntimeManifest {
  generatedAt: string | null;
  assets: Record<string, { url: string; sha256: string }>;
}

export const RUNTIME_MANIFEST: RuntimeManifest = {
  generatedAt: null,
  assets: {},
};
