// GENERATED by `npm run runtime:push` — do not edit by hand.
//
// Maps the logical runtime keys stored in `templates.runtime_keys` to the
// content-addressed CDN objects that actually hold the bytes (ADR-0017).
// Committed on purpose: the app reads it at build time, so resolving a unit URL
// costs no network call on the ad path.
//
// TypeScript rather than JSON so it loads identically under the Next bundler and
// under plain `node` (which demands an import attribute for JSON), and so the
// shape is type-checked.

export interface RuntimeManifest {
  generatedAt: string | null;
  assets: Record<string, { url: string; sha256: string }>;
}

export const RUNTIME_MANIFEST: RuntimeManifest = {
  "generatedAt": "2026-09-28T09:20:26.984Z",
  "assets": {
    "age-gate/vpaid.js": {
      "url": "https://gr2mdnykh85uvpdw.public.blob.vercel-storage.com/runtime/age-gate/vpaid.4520da19.js",
      "sha256": "4520da199483c2fb85975daa32bcc218bd3d77fd0b3a04582b7fc25fa5429a4e"
    },
    "pick-message/vpaid.js": {
      "url": "https://gr2mdnykh85uvpdw.public.blob.vercel-storage.com/runtime/pick-message/vpaid.175f2616.js",
      "sha256": "175f26163a575ef55c62b5584ccf0c5d0f2682e560fef17c6e0e5010ed6b5c3a"
    },
    "quiz/vpaid.js": {
      "url": "https://gr2mdnykh85uvpdw.public.blob.vercel-storage.com/runtime/quiz/vpaid.37dcc1db.js",
      "sha256": "37dcc1db7984268a6fb85e9a82b2096c8596e15c78943577b25eb2bac7fd1f2d"
    },
    "scratch-reveal/vpaid.js": {
      "url": "https://gr2mdnykh85uvpdw.public.blob.vercel-storage.com/runtime/scratch-reveal/vpaid.8e6a22e7.js",
      "sha256": "8e6a22e7d3fe4fd0d6ef96c4afbc1120fd7b374a1d397a2a8ce6920c844d1752"
    },
    "shoppable/simid/index.html": {
      "url": "https://gr2mdnykh85uvpdw.public.blob.vercel-storage.com/runtime/shoppable/simid/index.ede9a3a6.html",
      "sha256": "ede9a3a68d0cde4ce17cca4c227d069d8ac56907149048f8eff79c2b7818f77c"
    },
    "shoppable/vpaid/unit.js": {
      "url": "https://gr2mdnykh85uvpdw.public.blob.vercel-storage.com/runtime/shoppable/vpaid/unit.92d15ed5.js",
      "sha256": "92d15ed5620e02a3e989c154e91ecfa65788570c03d10d9ab7eb12d31398f082"
    },
    "slider/vpaid.js": {
      "url": "https://gr2mdnykh85uvpdw.public.blob.vercel-storage.com/runtime/slider/vpaid.0cd16f95.js",
      "sha256": "0cd16f953319896c7cf54f29169c5a68433bb50d1c4ebe108aebeba784ea9719"
    }
  }
};
