/**
 * Upload the built runtime units to the **public** Vercel Blob store and write
 * `runtime/manifest.ts`.
 *
 *   npm run runtime:push          # every unit
 *   npm run runtime:push quiz     # only keys starting with "quiz"
 *
 * Objects are **content-addressed**: `runtime/<key>.<sha256[0..8]>.<ext>`. That is
 * what makes real CDN delivery possible. The previous scheme put a 120s signed
 * token in the URL, so the URL changed every minute and every change was a cache
 * miss plus a function invocation on the ad path (ADR-0015 / ADR-0017). A hashed
 * URL never changes for the same bytes, so it caches for a year and the player
 * fetches it straight from Vercel's CDN.
 *
 * Two consequences worth stating plainly:
 *   - The unit JS becomes permanently fetchable by anyone holding the URL. That
 *     costs nothing: the advertiser's config travels in the VAST `<AdParameters>`,
 *     not in this file, so a cancelled subscription still yields an empty VAST and
 *     the saved URL only serves an anonymous template. ADR-0003 already concedes
 *     the code is inspectable.
 *   - Superseded hashes are not deleted. They are small and immutable; pruning
 *     them would risk breaking a VAST document still cached at the edge.
 *
 * SIMID's `index.html` ships here too but is still served through
 * `/api/creative/simid/[token]`, because Blob (like Supabase Storage before it)
 * forces `content-disposition: attachment` on HTML, which stops an iframe from
 * running it.
 *
 * Needs RUNTIME_BLOB_READ_WRITE_TOKEN — the *public* store's token, separate from
 * the private snapshot store's BLOB_READ_WRITE_TOKEN. Nothing here logs it.
 */
import { put } from "@vercel/blob";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const MANIFEST_PATH = join(root, "runtime", "manifest.ts");

/** Kept in step with the hand-written header in runtime/manifest.ts. */
const MANIFEST_HEADER = `// GENERATED by \`npm run runtime:push\` — do not edit by hand.
//
// Maps the logical runtime keys stored in \`templates.runtime_keys\` to the
// content-addressed CDN objects that actually hold the bytes (ADR-0017).
// Committed on purpose: the app reads it at build time, so resolving a unit URL
// costs no network call on the ad path.
//
// TypeScript rather than JSON so it loads identically under the Next bundler and
// under plain \`node\` (which demands an import attribute for JSON), and so the
// shape is type-checked.

export interface RuntimeManifest {
  generatedAt: string | null;
  assets: Record<string, { url: string; sha256: string }>;
}
`;

const token = process.env.RUNTIME_BLOB_READ_WRITE_TOKEN;
if (!token) {
  console.error(
    "RUNTIME_BLOB_READ_WRITE_TOKEN is not set.\n" +
      "This is the PUBLIC blob store that holds the creative runtime — a different\n" +
      "store from the private one the serving snapshots use.\n" +
      "Vercel dashboard -> Storage -> create a Blob store with access Public ->\n" +
      "connect it to the project -> copy its read/write token into .env.local.",
  );
  process.exit(1);
}

const CONTENT_TYPE = {
  ".js": "application/javascript",
  ".html": "text/html",
};

/** A year. Safe because the object key contains a hash of its own bytes. */
const CACHE_MAX_AGE = 31_536_000;

/** Every file under runtime/dist, keyed by its path relative to dist/. */
function distFiles(dir = join(root, "runtime", "dist"), out = []) {
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) distFiles(p, out);
    else out.push(p);
  }
  return out;
}

const distRoot = join(root, "runtime", "dist");
const uploads = distFiles().map((path) => ({
  path,
  key: relative(distRoot, path).split("\\").join("/"),
}));

// The one unit build.mjs does not produce: SIMID is a static document, not a
// concatenated VPAID unit, so it ships straight from source.
const simid = join(root, "runtime", "shoppable", "simid", "index.html");
if (existsSync(simid)) {
  uploads.push({ path: simid, key: "shoppable/simid/index.html" });
}

if (uploads.length === 0) {
  console.error("nothing to upload — run `npm run build:runtime` first");
  process.exit(1);
}

const filter = process.argv[2];
const selected = filter ? uploads.filter((u) => u.key.startsWith(filter)) : uploads;
if (selected.length === 0) {
  console.error(`no runtime key starts with "${filter}". Available:`);
  for (const u of uploads) console.error(`  ${u.key}`);
  process.exit(1);
}

/** `a/b/unit.js` + hash -> `runtime/a/b/unit.<hash8>.js` */
function hashedObjectKey(logicalKey, sha256) {
  const dot = logicalKey.lastIndexOf(".");
  const stem = logicalKey.slice(0, dot);
  const ext = logicalKey.slice(dot);
  return `runtime/${stem}.${sha256.slice(0, 8)}${ext}`;
}

// A partial push must not produce a partial manifest: start from what is already
// recorded so `npm run runtime:push quiz` updates one entry and leaves the rest.
// Imported rather than parsed — Node strips the types itself, and it keeps one
// definition of the file's shape instead of a parser here and a type there.
let assets = {};
if (existsSync(MANIFEST_PATH)) {
  try {
    const existing = await import(pathToFileURL(MANIFEST_PATH).href);
    assets = { ...(existing.RUNTIME_MANIFEST?.assets ?? {}) };
  } catch (err) {
    console.error(`could not read the existing manifest (${err.message}) — rewriting it`);
  }
}

let failed = 0;
for (const { path, key: logicalKey } of selected) {
  const body = readFileSync(path);
  const sha256 = createHash("sha256").update(body).digest("hex");
  const objectKey = hashedObjectKey(logicalKey, sha256);
  const ext = logicalKey.slice(logicalKey.lastIndexOf("."));

  try {
    const blob = await put(objectKey, body, {
      access: "public",
      token,
      contentType: CONTENT_TYPE[ext] ?? "application/octet-stream",
      addRandomSuffix: false,
      // Re-pushing identical bytes lands on the same key; allow it so a repeated
      // push is a no-op rather than an error.
      allowOverwrite: true,
      cacheControlMaxAge: CACHE_MAX_AGE,
    });
    assets[logicalKey] = { url: blob.url, sha256 };
    console.log(`  ${logicalKey.padEnd(32)} ${String(body.length).padStart(7)} bytes  ${sha256.slice(0, 8)}`);
  } catch (err) {
    console.error(`  FAILED ${logicalKey}: ${err.message}`);
    failed++;
  }
}

if (failed) {
  console.error(`\n${failed} upload(s) failed — manifest not written`);
  process.exit(1);
}

// Keys sorted so a re-push produces a byte-identical file when nothing changed,
// and a diff that shows only what moved when something did.
const sorted = Object.fromEntries(
  Object.entries(assets).sort(([a], [b]) => a.localeCompare(b)),
);
const manifest = { generatedAt: new Date().toISOString(), assets: sorted };

writeFileSync(
  MANIFEST_PATH,
  `${MANIFEST_HEADER}\nexport const RUNTIME_MANIFEST: RuntimeManifest = ${JSON.stringify(
    manifest,
    null,
    2,
  )};\n`,
);

console.log(`\n${selected.length} object(s) pushed`);
console.log(`manifest written to runtime/manifest.ts — COMMIT IT before deploying,`);
console.log(`the app reads it at build time to resolve unit URLs.`);
