import { describeIabError } from "./errors-iab";
import type { InspectReport, Severity } from "./model";

/**
 * The report as plain text.
 *
 * This is the deliverable, not a convenience: nothing about a validation run is
 * stored, so the way a result travels to a colleague is that the person who ran
 * it copies this out. That makes it worth composing properly — it has to stand
 * on its own in an email or a ticket, without the page around it.
 *
 * Fixed-width columns and a stable section order keep two runs diffable, which
 * is how anyone checks whether last week's fix actually landed.
 */

type Locale = "ru" | "en";

const LABELS = {
  ru: {
    title: "ОТЧЁТ ПРОВЕРКИ VAST",
    generated: "Сформирован",
    source: "Источник",
    pastedXml: "вставленный XML",
    verdict: "Вердикт",
    version: "Версия VAST",
    versionUnknown: "не объявлена",
    ads: "Объявлений",
    hops: "Переходов в цепочке",
    bytes: "Загружено",
    summary: "СВОДКА",
    chain: "ЦЕПОЧКА ОБЁРТОК",
    features: "ВОЗМОЖНОСТИ",
    interactive: "ИНТЕРАКТИВНЫЕ СТАНДАРТЫ",
    findings: "НАХОДКИ",
    trackers: "ТРЕКИНГ",
    recommendations: "РЕКОМЕНДАЦИИ",
    noFindings: "Нарушений не найдено.",
    noTrackers: "Трекинговых URL не найдено.",
    notPresent: "не обнаружен",
    present: "обнаружен",
    since: "с версии",
    deprecated: "устарел с",
    removed: "исключён в",
    unavailable: "недоступно при объявленной версии",
    // Same wording and same label-then-count order as the on-screen report:
    // this text is what a colleague receives, and it should read as the same
    // document. See the note in lib/i18n/dictionaries.ts.
    errors: "Ошибки",
    warnings: "Предупреждения",
    advisories: "Советы",
    line: "строка",
    degraded: "АНАЛИЗ НЕПОЛНЫЙ — эти правила завершились с ошибкой и не отработали:",
    footer: "Сформировано CreoSmith VAST Validator",
    truncated: "и ещё",
    severity: { error: "ОШИБКА", warning: "ВНИМАНИЕ", advisory: "СОВЕТ" },
    verdicts: { pass: "ПРОЙДЕНО", warn: "С ЗАМЕЧАНИЯМИ", fail: "НЕ ПРОЙДЕНО" },
  },
  en: {
    title: "VAST VALIDATION REPORT",
    generated: "Generated",
    source: "Source",
    pastedXml: "pasted XML",
    verdict: "Verdict",
    version: "VAST version",
    versionUnknown: "not declared",
    ads: "Ads",
    hops: "Chain hops",
    bytes: "Downloaded",
    summary: "SUMMARY",
    chain: "WRAPPER CHAIN",
    features: "CAPABILITIES",
    interactive: "INTERACTIVE STANDARDS",
    findings: "FINDINGS",
    trackers: "TRACKING",
    recommendations: "RECOMMENDATIONS",
    noFindings: "No violations found.",
    noTrackers: "No tracking URLs found.",
    notPresent: "not present",
    present: "present",
    since: "since",
    deprecated: "deprecated in",
    removed: "removed in",
    unavailable: "unavailable at the declared version",
    errors: "Errors",
    warnings: "Warnings",
    advisories: "Advisories",
    line: "line",
    degraded: "ANALYSIS INCOMPLETE — these rules threw and did not run:",
    footer: "Generated by the CreoSmith VAST Validator",
    truncated: "and",
    severity: { error: "ERROR", warning: "WARNING", advisory: "ADVISORY" },
    verdicts: { pass: "PASS", warn: "PASS WITH WARNINGS", fail: "FAIL" },
  },
} as const;

const RULE = "─".repeat(72);

function heading(text: string): string {
  return `\n${text}\n${RULE}`;
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/** Long URLs are trimmed so one tracker cannot swallow a whole screen. */
function clip(value: string, max = 96): string {
  return value.length <= max ? value : `${value.slice(0, max - 1)}…`;
}

export function renderReportText(report: InspectReport, locale: Locale): string {
  const t = LABELS[locale];
  const lines: string[] = [];

  lines.push(t.title);
  lines.push(RULE);
  lines.push(`${t.generated}: ${report.generatedAt}`);
  lines.push(`${t.source}: ${report.source.mode === "url" ? report.source.url : t.pastedXml}`);

  // Before anything else, and before the verdict in particular: a reader must
  // not take "no violation" from a run where a check never executed. This text
  // travels to a colleague with no page around it, so the caveat has to be in it.
  if (report.degraded && report.degraded.length > 0) {
    lines.push("");
    lines.push(t.degraded);
    lines.push(`  ${[...new Set(report.degraded)].join(", ")}`);
  }

  lines.push(heading(t.summary));
  lines.push(`${t.verdict}: ${t.verdicts[report.verdict]}`);
  lines.push(
    `${t.errors} ${report.counts.error} · ${t.warnings} ${report.counts.warning} · ${t.advisories} ${report.counts.advisory}`,
  );
  lines.push(`${t.version}: ${report.declaredVersion ?? t.versionUnknown}`);
  lines.push(`${t.ads}: ${report.adCount}`);
  lines.push(`${t.hops}: ${report.chain.length}`);
  lines.push(`${t.bytes}: ${formatBytes(report.source.bytes)}`);

  if (report.chain.length > 0) {
    lines.push(heading(t.chain));
    for (const hop of report.chain) {
      const status = hop.status !== undefined ? `HTTP ${hop.status}` : "—";
      const timing = hop.elapsedMs > 0 ? `${hop.elapsedMs} ms` : "—";
      lines.push(
        `#${hop.index}  ${hop.kind.padEnd(8)} ${status.padEnd(9)} ${timing.padEnd(8)} ${formatBytes(hop.bytes).padEnd(9)} ${clip(hop.url, 60)}`,
      );
      if (hop.adSystem) lines.push(`     AdSystem: ${hop.adSystem}`);
      if (hop.error) lines.push(`     ! ${hop.error[locale]}`);
    }
  }

  lines.push(heading(t.interactive));
  for (const hit of report.interactive) {
    lines.push(`${hit.standard.padEnd(6)} ${hit.present ? t.present : t.notPresent}`);
    if (hit.present && hit.resource) lines.push(`       ${clip(hit.resource)}`);
    for (const note of hit.notes) lines.push(`       ${note[locale]}`);
  }

  lines.push(heading(t.features));
  for (const feature of report.features) {
    const mark = feature.present ? "[x]" : "[ ]";
    const meta: string[] = [`${t.since} ${feature.since}`];
    if (feature.deprecatedIn) meta.push(`${t.deprecated} ${feature.deprecatedIn}`);
    if (feature.removedIn) meta.push(`${t.removed} ${feature.removedIn}`);
    if (!feature.availableAtDeclaredVersion) meta.push(t.unavailable);
    lines.push(`${mark} ${feature.label[locale].padEnd(38)} ${meta.join(", ")}`);
    if (feature.present && feature.detail) lines.push(`    ${feature.detail}`);
  }

  lines.push(heading(t.findings));
  if (report.findings.length === 0) {
    lines.push(t.noFindings);
  } else {
    for (const finding of report.findings) {
      const severity = t.severity[finding.severity as Severity];
      const where = finding.line ? `${finding.path} (${t.line} ${finding.line})` : finding.path;
      lines.push("");
      lines.push(`[${severity}] ${finding.message[locale]}`);
      lines.push(`  ${finding.ruleId} · ${finding.spec.doc} ${finding.spec.section}`);
      lines.push(`  ${where}${finding.hop > 0 ? ` · hop #${finding.hop}` : ""}`);
      if (finding.offending) lines.push(`  → ${clip(finding.offending)}`);
      if (finding.iabErrorCode !== undefined) {
        lines.push(`  IAB ${describeIabError(finding.iabErrorCode, locale)}`);
      }
      lines.push(`  ${finding.hint[locale]}`);
    }
  }

  lines.push(heading(t.trackers));
  if (report.trackers.length === 0) {
    lines.push(t.noTrackers);
  } else {
    // The inventory can run to hundreds of rows on a long chain; a shared
    // report needs to stay readable, and the full list is in the JSON export.
    const shown = report.trackers.slice(0, 60);
    for (const tracker of shown) {
      const kind = tracker.event ? `${tracker.kind}:${tracker.event}` : tracker.kind;
      lines.push(`#${tracker.hop}  ${kind.padEnd(28)} ${clip(tracker.url, 80)}`);
    }
    if (report.trackers.length > shown.length) {
      lines.push(`… ${t.truncated} ${report.trackers.length - shown.length}`);
    }
  }

  if (report.recommendations.length > 0) {
    lines.push(heading(t.recommendations));
    report.recommendations.forEach((item, index) => {
      lines.push("");
      lines.push(`${index + 1}. ${item.title[locale]}`);
      lines.push(`   ${item.body[locale]}`);
    });
  }

  lines.push("");
  lines.push(RULE);
  lines.push(t.footer);

  return lines.join("\n");
}
